name: macOS

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Install Dependencies
        run: brew install qt

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_QT6=ON -DUSE_TESTS=ON

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/build/lib/test
        shell: bash
        run: ${{runner.workspace}}/build/lib/test/spotify-qt-lib-test

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: spotify-qt
          path: ${{runner.workspace}}/build/spotify-qt
