name: Check for library updates

on:
  schedule:
    - cron: '0 12 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update
        working-directory: ${{runner.workspace}}/res
        run: python update.py
